# Generated by Django 4.0.3 on 2022-04-15 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bckend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
        migrations.CreateModel(
            name='UserPicture',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('picture', models.FileField(upload_to='pictures')),
                ('userid', models.ForeignKey(blank=True, db_column='userID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='picuserid', to='bckend.user')),
            ],
            options={
                'db_table': 'UserPicture',
                'managed': True,
            },
        ),
    ]
